# Generated by Django 4.2 on 2026-01-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(default='IT', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=2),
        ),
    ]
