# Generated by Django 4.2 on 2026-01-13 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='podcast/logos/')),
                ('main_url', models.URLField(help_text='Link to main podcast page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Podcast Series',
                'verbose_name_plural': 'Podcast Series',
            },
        ),
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('episode_number', models.IntegerField()),
                ('air_date', models.DateField()),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('audio_url', models.URLField(blank=True, help_text='Link to audio file', null=True)),
                ('video_url', models.URLField(blank=True, help_text='Link to video (YouTube, etc.)', null=True)),
                ('spotify_url', models.URLField(blank=True, null=True)),
                ('apple_podcasts_url', models.URLField(blank=True, null=True)),
                ('guest_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500, null=True)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.podcastseries')),
            ],
            options={
                'verbose_name': 'Podcast Episode',
                'verbose_name_plural': 'Podcast Episodes',
                'ordering': ['-air_date'],
                'unique_together': {('series', 'episode_number')},
            },
        ),
    ]
