# Generated by Django 4.2 on 2026-01-13 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_mentors', to='core.userprofile')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentored_interns', to='core.userprofile')),
                ('program', models.ForeignKey(limit_choices_to={'type': 'internship'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignments', to='core.program')),
            ],
        ),
        migrations.CreateModel(
            name='InternTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('assigned_on', models.DateField(auto_now_add=True)),
                ('program', models.ForeignKey(limit_choices_to={'type': 'internship'}, on_delete=django.db.models.deletion.CASCADE, related_name='intern_tasks', to='core.program')),
            ],
        ),
        migrations.CreateModel(
            name='InternSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='internship.interntask')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intern_submissions', to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InternProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diploma_student', models.BooleanField(default=False)),
                ('degree_student', models.BooleanField(default=False)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intern_profile', to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InternCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_on', models.DateField(auto_now_add=True)),
                ('certificate_file', models.FileField(blank=True, upload_to='intern_certificates/')),
                ('program', models.ForeignKey(limit_choices_to={'type': 'internship'}, on_delete=django.db.models.deletion.CASCADE, related_name='intern_certificates', to='core.program')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intern_certificates', to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InternApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('program', models.ForeignKey(limit_choices_to={'type': 'internship'}, on_delete=django.db.models.deletion.CASCADE, related_name='intern_applications', to='core.program')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intern_applications', to='core.userprofile')),
            ],
        ),
    ]
