# Generated by Django 4.2 on 2026-01-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_name_08fd2e_idx',
            old_name='products_na_name_c545fb_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_categor_49270f_idx',
            old_name='products_ca_cate_3b78d9_idx',
        ),
    ]
